function AcWeakLineInstab(prn)

close all
% prn=1;
% LCpower(prn)
% se prn=1 salva le figure power.eps

%% Local Variables
nx = 1;			% Numero di figure in orizzontale
ny = 2;			% Numero di figure in verticale
bx = 0.30;	    % Margini sinistro  e destro    [cm]
by = 0.28;		% Margini superiore e inferiore [cm]
fx = 7.30;		% Larghezza primo riquadro interno [cm]
fy = 1.5;		% Altezza riquadri interni   [cm]
dx = 0.0;		% Distanza orizzontale tra i riquadri [cm]
dy = 0.28;		% Distanza verticale tra i riquadri   [cm]
ox = 0.6;		% Offset orizzontale [cm]
oy = 0.06;		% Offset verticale   [cm]
ospl = 0.0;
fnt  = 8;		% Dimensione dei font per gli assi
fnl  = 8;		% Dimensione dei font per le labels
fnl2 = 7;		% Dimensione dei font per le labels

fwidth  = nx*fx+(nx-1)*dx+2*bx+ox
fheigth = ny*fy+(ny-1)*dy+2*by+ospl;

if fwidth > 8.5
    disp('Error. Plot wider than single column')
    return
end
%%
lincol5=[0 0 0];            % black
lincol3=0.75*[1 1 1];       % gray
lincol7=0.5*[1 1 1];        % gray
lincol8=0.25*[1 1 1];
blue = [57 106 177]./255;
red = [204 37 41]./255;
linwid1=0.5;              % spessore 1
linwid2=1.5;              % spessore 2
%% Creazione Figura
figure('Renderer', 'Painters',...
    'units','centimeters',...
    'position',[bx, by, fwidth, fheigth], ...
    'PaperUnits','centimeters', ...
    'PaperOrientation','portrait', ...
    'PaperPosition',[bx, by, fwidth, fheigth], ...
    'PaperType','A4', ...
    'Color','white' ...
    );
%%
% Creazione Riquadri e Grafici
% #format table ## [WaveView Analyzer] saved 16:33:34 Sun Mar 17 2019
% XVAL Ir Irdw Irup Is Isdw Isup It Itdw Itup Mcbn.Iarc Vr Vrdw Vrup Vs Vsdw Vsup Vt Vtdw Vtup neu Vndw Vnup
load('acInstability.mat');

DEC = 1;
time = time(1:DEC:end);
Isg1 = Isg1(1:DEC:end);
Isg2 = Isg2(1:DEC:end);
Isg3 = Isg3(1:DEC:end);
Iwg1 = Iwg1(1:DEC:end);
Iwg2 = Iwg2(1:DEC:end);
Iwg3 = Iwg3(1:DEC:end);

%%


for i=1:nx
    for j=1:ny
        h(i,j)=axes(...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'box','on', ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'XTick', [], ...
            'Ytick', [], ...
            'XLim', [1.8 2.03]);
        
        OFF = 0;
        
        if j==1
             line(time,Isg2,'Color', red, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            line(time,Isg3,'Color', blue, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            line(time,Isg1,'Color', lincol5, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
           
            
        elseif j==2
            
            line(time,Iwg2,'Color', red, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            line(time,Iwg3,'Color', blue, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            line(time,Iwg1,'Color', lincol5, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            
            
        end
        
        set(h(i,j),'Xgrid', 'on', 'Ygrid', 'on');
        
        if j==1
        set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'Xscale','linear');
        
        elseif j==2
                    set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'YLim', [-3.6e3 3.6e3], ...
            'Xscale','linear');
        end
        
        if j==1
            format_ticks(h(i,j),{'$ $','$ $','$ $','$ $','$ $','$ $'},...
                {'$-6$','$0$','$6$','$12$'},...
                [1.8 1.86 1.92 1.97 2.00 2.03], linspace(-6,12,4),[],[],[0.020 0.020]);
            axlbl={'$$t [\mathrm{s}]$$','$$i_{\mathrm{a,b,c}} [\mathrm{A}] $$'};
            
            lt=[0.01, 0.72];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
            
        elseif j==2

            format_ticks(h(i,j),{'$1.80$','$1.86$','$1.92$','$1.97$','$2.00$','$2.03$'},...
                {'$-3.6$','$1.8$','$0$','$1.8$','$3.6$'},...
                [1.8 1.86 1.92 1.97 2.00 2.03], linspace(-3.6e3,3.6e3,5),[],[],[0.060 0.020]);
            axlbl={'$$t [\mathrm{s}]$$','$$i_{\mathrm{a,b,c}} [\mathrm{kA}] $$'};
            
            lt=[1.00, 0.005];
            text(h(i,j),lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','right',...
                'VerticalAlignment','bottom', ...
                'Color', 'black', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.01, 0.72];
            text(h(i,j),lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
            
        end
    end
end


% 
% inset2 = axes(...
%     'units','normalized',...
%     'position',[0.6 0.1, 0.25 0.15],...
%     'fontsize',fnt,...
%     'fontname','helvetica',...
%     'fontangle','normal',...
%     'visible','on', ...
%     'Color','none', ...
%     'box','on', ...
%     'XTickLabel', [], ...
%     'YTickLabel', [], ...
%     'XTick', [], ...
%     'Ytick', [], ...
%     'XLim', [1.86 1.92]);
% 
% line(time,Iwg1,'Color', lincol5, ...
%     'LineWidth',  linwid1,...
%     'Linestyle','-');
% 
% hold on
% 
% line(time,Iwg2,'Color', lincol3, ...
%     'LineWidth',  linwid1,...
%     'Linestyle','-');
% 
% line(time,Iwg3,'Color', lincol7, ...
%     'LineWidth',  linwid1,...
%     'Linestyle','-');
% 
% set(inset2, 'Xgrid', 'on', 'Ygrid', 'on');
% 
% format_ticks(inset2,{'$1.86$','$1.89$','$1.92$'},...
%     {'$-0.05$','$0$','$0.05$'},...
%     [1.86 1.89 1.92], linspace(-50e-3,50e-3,3),[],[],[0.020 0.020]);
% axlbl={'$$t [\mathrm{s}]$$','$$i_{\mathrm{a,b,c}} [\mathrm{A}] $$'};
% 
% 
% lt=[0.01, 0.72];
% text(inset2,lt(1),lt(2),axlbl{2}, ...
%     'fontname','times',...
%     'fontangle','italic',...
%     'fontsize',fnl*0.5, ...
%     'fontweight', 'normal', ...
%     'interpreter','latex',...
%     'HorizontalAlignment','l',...
%     'VerticalAlignment','bottom', ...
%     'Unit', 'normalized' ...
%     );

if(prn)
    print -loose -painters -depsc2 ..\figs\AcWeakLineInstab.eps
end